apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
  namespace: lab-k8s
  labels:
    app: demo-k8s
spec:
  type: NodePort
  selector:
    app: demo-k8s
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084